name: TICK

on:
  schedule:
      - cron:  '30 20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: tick!
        run: echo $(date) > lastTick.txt
        
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Add tick file'
          add: '*.txt --force'
